// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHolding(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function AddWatchlist(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CorrectHoldingCost(arg1:string,arg2:number):Promise<void>;

export function GetActionAdvice():Promise<string>;

export function GetAnalysisReport():Promise<string>;

export function GetCalendar(arg1:number):Promise<string>;

export function GetConfig():Promise<string>;

export function GetConfigFile():Promise<string>;

export function GetDashboard():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetDividendSummary():Promise<string>;

export function GetFundInfo():Promise<string>;

export function GetGridStrategy(arg1:string):Promise<string>;

export function GetHoldingGrid(arg1:string):Promise<string>;

export function GetPortfolio():Promise<string>;

export function GetStockDetail(arg1:string):Promise<string>;

export function GetTrackingStocks():Promise<string>;

export function GetWatchlist():Promise<string>;

export function RefreshStock(arg1:string):Promise<string>;

export function RemoveHolding(arg1:string):Promise<void>;

export function RemoveWatchlist(arg1:string):Promise<void>;

export function SaveHoldingGrid(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchStock(arg1:string):Promise<string>;

export function SetAvailableFund(arg1:number):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetLifecycleStage(arg1:number):Promise<void>;

export function UpdateHolding(arg1:string,arg2:number):Promise<void>;

export function UpdateWatchlist(arg1:string,arg2:string,arg3:number):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleFullscreen():Promise<void>;
