// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHolding(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddHolding'](arg1, arg2, arg3, arg4);
}

export function AddWatchlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWatchlist'](arg1, arg2, arg3);
}

export function CompareStocks(arg1, arg2) {
  return window['go']['main']['App']['CompareStocks'](arg1, arg2);
}

export function GetAnalysisReport() {
  return window['go']['main']['App']['GetAnalysisReport']();
}

export function GetCalendar(arg1) {
  return window['go']['main']['App']['GetCalendar'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigFile() {
  return window['go']['main']['App']['GetConfigFile']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDividendSummary() {
  return window['go']['main']['App']['GetDividendSummary']();
}

export function GetFundInfo() {
  return window['go']['main']['App']['GetFundInfo']();
}

export function GetGridStrategy(arg1) {
  return window['go']['main']['App']['GetGridStrategy'](arg1);
}

export function GetPension(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPension'](arg1, arg2, arg3, arg4);
}

export function GetPortfolio() {
  return window['go']['main']['App']['GetPortfolio']();
}

export function GetStockDetail(arg1) {
  return window['go']['main']['App']['GetStockDetail'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function RealEstateToEquity(arg1, arg2, arg3) {
  return window['go']['main']['App']['RealEstateToEquity'](arg1, arg2, arg3);
}

export function RefreshStock(arg1) {
  return window['go']['main']['App']['RefreshStock'](arg1);
}

export function RemoveHolding(arg1) {
  return window['go']['main']['App']['RemoveHolding'](arg1);
}

export function RemoveWatchlist(arg1) {
  return window['go']['main']['App']['RemoveWatchlist'](arg1);
}

export function SearchStock(arg1) {
  return window['go']['main']['App']['SearchStock'](arg1);
}

export function SetAvailableFund(arg1) {
  return window['go']['main']['App']['SetAvailableFund'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetLifecycleStage(arg1) {
  return window['go']['main']['App']['SetLifecycleStage'](arg1);
}

export function UpdateHolding(arg1, arg2) {
  return window['go']['main']['App']['UpdateHolding'](arg1, arg2);
}

export function UpdateWatchlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWatchlist'](arg1, arg2, arg3);
}
